workspace = { members = [ "fruits_alloc_monitor", "fruits_app", "fruits_example/fruits_example_cubes", "fruits_example/fruits_example_boids", "fruits_math", "fruits_modules", "fruits_utils", "hlib_test" , "fruits_ecs_macros", "fruits_serialization", "fruits_gui_old", "fruits_ecs", "fruits_example/fruits_example_ecs", "fruits_example/fruits_example_gizmos", "fruits_swizzling", "fruits_example/fruits_example_collisions", "fruits_reflection", "fruits_example/fruits_example_text", "fruits_debug", "fruits_example/fruits_example_ui", "fruits_reflection_macros", "fruits_gui", "fruits_ffi", "fruits_ecs_core", "fruits_ecs_core_sample_dylib"] }

[package]
name = "fruits_engine"
version = "0.3.0"
edition = "2024"

[lib]
crate-type = ["lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fruits_app = { path = "./fruits_app" }
fruits_ecs = { path = "./fruits_ecs" }
fruits_modules = { path = "./fruits_modules" }
fruits_utils = { path = "./fruits_utils" }
fruits_math = { path = "./fruits_math" }
fruits_serialization = { path = "./fruits_serialization" }
fruits_reflection = { path = "./fruits_reflection" }
