[workspace]
members = [
    "fruits_alloc_monitor",
    "fruits_audio",
    "fruits_app",
    "fruits_example/fruits_example_cubes",
    "fruits_example/fruits_example_boids",
    "fruits_math",
    "fruits_modules",
    "fruits_utils",
    "hlib_test",
    "fruits_ecs_macros",
    "fruits_serialization",
    "fruits_ecs",
    "fruits_example/fruits_example_ecs",
    "fruits_example/fruits_example_gizmos",
    "fruits_swizzling",
    "fruits_example/fruits_example_collisions",
    "fruits_reflection",
    "fruits_example/fruits_example_text",
    "fruits_debug",
    "fruits_example/fruits_example_ui",
    "fruits_reflection_macros",
    "fruits_editor",
    "fruits_ffi",
    "fruits_math_macros",
    "fruits_entry_point",
    "fruits_app_launcher",
    "fruits_asset_loading",
    "fruits_asset_storage",
    "fruits_wavefront",
    "fruits_json_macros",
    "fruits_control_flow_macros",
    "fruits_render",
    "fruits_transform",
    "fruits_collision",
    "fruits_asset_storage",
    "fruits_render_core",
    "fruits_prefab",
    "fruits_json",
    "fruits_serialization_macros",
    "fruits_audio",
    "fruits_example/fruits_audio_screen_saver",
    "fruits_example/fruits_example_normals"
, "fruits_example/fruits_example_bloom"]

[package]
name = "fruits_engine"
version = "0.7.1"
edition = "2024"

[lib]
crate-type = ["lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fruits_app = { path = "./fruits_app" }
fruits_audio = { path = "./fruits_audio" }
fruits_ecs = { path = "./fruits_ecs" }
fruits_modules = { path = "./fruits_modules" }
fruits_utils = { path = "./fruits_utils" }
fruits_math = { path = "./fruits_math" }
fruits_math_macros = { path = "./fruits_math_macros" }
fruits_serialization = { path = "./fruits_serialization" }
fruits_reflection = { path = "./fruits_reflection" }
fruits_entry_point = { path = "./fruits_entry_point" }
fruits_app_launcher = { path = "./fruits_app_launcher" }
fruits_asset_loading = { path = "./fruits_asset_loading" }
fruits_asset_storage = { path = "./fruits_asset_storage" }
fruits_ffi = { path = "./fruits_ffi" }
fruits_control_flow_macros = { path = "./fruits_control_flow_macros" }
fruits_transform = { path = "./fruits_transform" }
fruits_render = { path = "./fruits_render" }
fruits_render_core = { path = "./fruits_render_core" }
fruits_collision = { path = "./fruits_collision" }
fruits_prefab = { path = "./fruits_prefab" }
fruits_json = { path = "./fruits_json" }
