[package]
name = "fruits_audio"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib"]

[dependencies]
rand = "0.10"
cpal = "0.17"
fruits_ecs = { path = "../fruits_ecs" }
fruits_asset_storage = { path = "../fruits_asset_storage" }
fruits_ffi = { path = "../fruits_ffi" }
fruits_serialization = { path = "../fruits_serialization" }