[package]
name = "fruits_ui"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib"]

[dependencies]
fruits_ecs = { path = "../fruits_ecs" }
fruits_asset_storage = { path = "../fruits_asset_storage" }
fruits_math = { path = "../fruits_math" }
fruits_render_core = { path = "../fruits_render_core" }
fruits_ffi = { path = "../fruits_ffi" }
fruits_transform = { path = "../fruits_transform" }
fruits_render = { path = "../fruits_render" }
image = "0.25"