[package]
name = "fruits_render"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib"]

[dependencies]
wgpu = "26"
image = "0.25"
fruits_math = { path = "../fruits_math" }
fruits_ecs = { path = "../fruits_ecs" }
fruits_utils = { path = "../fruits_utils" }
fruits_transform = { path = "../fruits_transform" }
fruits_render_core = { path = "../fruits_render_core" }
fruits_asset_storage = { path = "../fruits_asset_storage" }
fruits_ffi = { path = "../fruits_ffi" }