[package]
name = "fruits_modules"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib"]

[dependencies]
fruits_ecs = { path = "../fruits_ecs" }
fruits_math = { path = "../fruits_math" }
fruits_utils = { path = "../fruits_utils" }
fruits_ffi = { path = "../fruits_ffi" }
wgpu = "26"
winit = "0.30.12"
image = "0.25.6"
pollster = "0.4"