[package]
name = "fruits_transform"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib"]

[dependencies]
fruits_ecs = { path = "../fruits_ecs" }
fruits_ffi = { path = "../fruits_ffi" }
fruits_math = { path = "../fruits_math" }
fruits_render_core = { path = "../fruits_render_core" }
serde = { version = "1", features = ["derive"] }