[package]
name = "fruits_prefab"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib"]

[dependencies]
fruits_ecs = { path = "../fruits_ecs" }
fruits_asset_storage = { path = "../fruits_asset_storage" }
fruits_render_core = { path = "../fruits_render_core" }
fruits_render = { path = "../fruits_render" }
fruits_audio = { path = "../fruits_audio" }
fruits_serialization = { path = "../fruits_serialization" }
fruits_ffi = { path = "../fruits_ffi" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }