[package]
name = "fruits_render_core"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib"]

[dependencies]
fruits_ecs = { path = "../fruits_ecs" }
fruits_ffi = { path = "../fruits_ffi" }
fruits_utils = { path = "../fruits_utils" }
fruits_serialization = { path = "../fruits_serialization" }
fruits_math = { path = "../fruits_math" }
fruits_asset_storage = { path = "../fruits_asset_storage" }
wgpu = "27"
winit = "0.30"
pollster = "0.4"